### ISSUE TITLE
DAR not correctly detected?

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#138]
I stumbled upon this video which I had stored and wanted to upscale.

Resolution: 854x480
Aspect Ratio: 16:9

```
Width                                    : 854 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
```

I use upscaling to -2x1080 which should produce an 1920x1080 but the video becomes 1944x1080 and 1:1.
When changing the DAR in the option file to 16:9 it works. 

Wanted to check if this is a problem with QSVENc or issue with the video.
When using MediaInfo the resolution and DAR is shown correctly.

**Comment by rigaya** [comment]
The calculation is correct, but problem is that 854x480 is not exactly 16:9.

When input is 854x480, only with ```--output-res -2x1080``` you will get 1922x1080, as (854/480)*1080=1921.5. This is near to 1922 rather than 1920, so 1922 will be selected.

With ```--dar 16:9 --output-res -2x1080``` you will get 1920x1080, as (16/9)*1080=1920.

You can try for ```--output-res -4x1080``` to round to multiple of 4, resulting 1920x1080 for even 854x480 without dar, as 1921.5 is near to 1920 rather than 1924.

**Comment by quamt** [comment]
Ok, will try that. Thank you.
