### ISSUE TITLE
Best memory config for QSVEnc?

### ISSUE THREAD

**Issue by Justuzz** [rigaya/QSVEnc#183]
Actually it is an issue to find reliable info on what memory modules to pick for running QSVEnc so that it benefits the most. I am currently running an Intel Arc750 with a Ryzen 3900 on Windows 10 with some left over incompatible modules (4x4GB, 2133Mhz, CL22) and need to get new memory sticks. 
What is best for QSVEnc, are 16GB enough or better 32GB? Is Timing more important than frequency, meaning is it better to choose for instance 3600Mhz CL18 before 3200 CL16? Cheers!

**Comment by rigaya** [comment]
QSVEnc does not require so much memory so 16GB will be enough, at least for up to 4K encoding.

I think memory bandwdith is required for QSVEnc in othe old DDR3 days, but DDR4 dual-channel memory speed will be enough. Below are the tests I've done for H.264, HEVC, HEVC 10bit with 1080p encoding.

You shall actually check for about GPU clock and EUs, rather than memory speed.

![QSVEnc_h264](https://blog-imgs-135.fc2.com/r/i/g/rigaya34589/qsv_benchmark_20220126_qsvencc_01.png)
![QSVEnc_hevc](https://blog-imgs-135.fc2.com/r/i/g/rigaya34589/qsv_benchmark_20220126_qsvencc_02.png)
![QSVEnc_hevc_10bit](https://blog-imgs-135.fc2.com/r/i/g/rigaya34589/qsv_benchmark_20220126_qsvencc_03.png)

**Comment by rigaya** [comment]
I'll close this issue as the topic has been answered.
